name: Deploy app to k8s
env:
  DOCKER_USER: ${{secrets.DOCKER_HUB_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_TOKEN}}
  DOCKER_REPOSITORY: my-app
  NODE_IMAGE_TAG: knote

on:
  push:
    branches: [ main]

permissions:
  actions: read
  security-events: write
  
jobs:
  
  deploy-app:
    
    name: Install kubectl and deploy app
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest' # default is latest stable
      id: install

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2

    # - name: install helm 
    #   uses: azure/setup-helm@v3
    #   with:
    #     version: 'latest' # default is latest (stable)
    #     token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
    #   id: install
    

    # - name: Pull Image from Docker Hub    
    #   run: |
    #     docker login -u ${{env.DOCKER_USER}} -p ${{env.DOCKER_PASSWORD}}
    #     docker pull ${{env.DOCKER_USER}}/${{env.DOCKER_REPOSITORY}}:${{env.NODE_IMAGE_TAG}}

    - name: Login to Docker Hub and pull the knote image
		  uses: docker/login-action@v2
		  with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    # - name:  update kubeconfig
    #   run : |
    #      aws eks update-kubeconfig --region us-east-2 --name prod

    - name: Set K8s context
      uses: ossrs/k8s-set-context-action@v1
      with:
        kubeconfig: '${{ secrets.KUBECONFIG }}'

    # - name: Run K8s
    #   run: |-
    #     kubectl cluster-info
      
    # - name: Set imagePullSecret
    #   run: |
        
    #     kubectl create secret docker-registry regcred --docker-server=https://index.docker.io/v1/ --docker-username=heder24 --docker-password=Imth@re@ld@de --docker-email=hederredon@gmail.com
        

    - name:  update kubeconfig
      run : |
         aws eks update-kubeconfig --region us-east-2 --name prod

    # - name: Deploy to EKS
    #   run: | 
    #     kubectl apply -f knote.yml
    #     kubectl apply -f minio.yml
    #     kubectl apply -f mongo.yml